incompatible chart versions removed
causing error message:
Error: validation failed: unable to recognize : no matches for kind Deployment in version extensions/v1beta1